#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
Pgrep -x panel > /dev/null || panel &

#bspc monitor HDMI1 -d 1 2
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           11

bspc config split_ratio          0.50
bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a R_x11 state=floating follow=on
bspc rule -a scrcpy follow=on desktop=next.!occupied
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Zathura state=fullscreen follow=on
bspc rule -a Emacs desktop='^2' state=monocle follow=on
bspc rule -a qutebrowser desktop='^9' state=monocle follow=on
